### ISSUE TITLE
efficient  wide sweeps for waveguide dispersion

### ISSUE THREAD

**Issue by KojaAMA** [HelgeGehring/femwell#112]
I am calculating the dispersion for different geometries. And mainly use loops for now. Is it possible to implement the calculations on arrays to avoid the loops? I think i need to redefine the mesh for every geometry but at least the wavelength sweep?  
https://helgegehring.github.io/femwell/photonics/examples/vary_wavelength.html#

**Comment by lucasgrjn** [comment]
Hi! I am not sure to understand what is your issue. Have you any code snippet to show what you mean? :)

**Comment by HelgeGehring** [comment]
At each wavelength it's an eigenvalue problem to solve which is described by a matrix. Combining such matrices will for sure increase the total computation time and lead to more problems :/

Some approaches which might help to speed it up:
- providing the `k0_guess` of the largest n_eff of the last set of modes (we should add a `n_eff_guess`) - might speed the solving a bit up, bit we should make sure to start with the system which has the largest n_eff
- providing a starting vector for the call to `eigs`, here the eigenvector with the largest n_eff might be a good guess
- precondition the assembled matrix with the previous eigenvectors - I'd guess this would increase the speed a lot as the eigenvectors should be very similar 🤔 I just don't have a clue how to do it right now 😅 (and we would need to have a look at points where modes cross in the spectrum, it might be that we miss find some modes which emerge while sweeping)

What's your application that you need such a fine wavelength resolution that the runtime becomes a problem?
