### ISSUE TITLE
pip install femwell

### ISSUE THREAD

**Issue by joamatab** [HelgeGehring/femwell#14]
Can you release a new version?

```
femwell depends on scikit-fem@ git+https://github.com/requests/requests.git
```

![image](https://user-images.githubusercontent.com/4514346/208798535-84c93250-0588-44aa-ad50-86c2f614af6e.png)

https://github.com/gdsfactory/gdsfactory/pull/1032/

**Comment by HelgeGehring** [comment]
Yes, I'll do a new release soon and then do it more often :) Up to now it was blocked by the usage of new features of scikit-fem, which were not yet in the papi release.

**Comment by joamatab** [comment]
nice, you can add `.bumpersion` to increase version number and tag the commits for each release

this may be helpful
https://github.com/joamatab/cookiecutter-pypackage-minimal

let us know when you upload the new version

@simbilod

**Comment by HelgeGehring** [comment]
I've just released a new version, now it should work!
The installation of slepc4py is still a bit complicated, I've described it in https://helgegehring.github.io/femwell/install.html , would be happy about an easier way :/

The release is now automatically done on new tags and the the version is automatically derived from the tag (https://github.com/HelgeGehring/femwell/blob/main/.github/workflows/release.yml)

I'll have a look on the template, thanks!

**Comment by joamatab** [comment]
it works :tada: 

it would be nicer to have a simpler install method

https://gitlab.com/petsc/petsc/-/issues/1303

**Comment by HelgeGehring** [comment]
Thanks for opening the issue!
The best option would be to have some pecompiled wheels, compiling petsc and slepc takes something like 10min :/

**Comment by HelgeGehring** [comment]
I'll close this one now, as we're now relying as the standard solver on scipy which is easy to install :)
