### ISSUE TITLE
python3.7 support

### ISSUE THREAD

**Issue by joamatab** [HelgeGehring/femwell#15]
How can we add python3.7 support?

that way we can use it in [binder](https://mybinder.org/v2/gh/gdsfactory/binder-sandbox/HEAD)

**Comment by HelgeGehring** [comment]
I wouldn't expect it to need a lot of changes, but it's easy to use a newer python version, see https://mybinder.readthedocs.io/en/latest/howto/languages.html
As the EOL of Python 3.7 isn't too far, I'd guess if this fixes it, we could just keep 3.8 as minimum?
