### ISSUE TITLE
Scipy bug

### ISSUE THREAD

**Issue by simbilod** [HelgeGehring/femwell#23]
The new scipy backend fails with

scipy.sparse.linalg._eigen.arpack.arpack.ArpackError: ARPACK error -9999: Could not build an Arnoldi factorization. IPARAM(5) returns the size of the current Arnoldi factorization. The user is advised to check that enough workspace and array storage has been allocated.

the same problem used to work well with slepc

**Comment by HelgeGehring** [comment]
I think this problems should be solved in the newest version. The automatic guess for `n_eff` was in some cases too far off and gave scipy problems
@simbilod could you confirm this is fixed also for your case?
