### ISSUE TITLE
Units in femwell

### ISSUE THREAD

**Issue by HelgeGehring** [HelgeGehring/femwell#29]
At the moment the units in the labels are a bit mixed in their format, e.g. for seconds:

- t [s] (which I mostly used up to now)
- t (s)
- t / s

The last one is according to https://academia.stackexchange.com/questions/18357/are-there-any-guidelines-for-labeling-axes-in-plots-graphs the preferred formatting according to the International System of Units

should we just stick to the last one?

@simbilod

**Comment by simbilod** [comment]
I think we should make [Pint ](https://github.com/hgrecco/pint) a dependency

In notebooks and scripts, the user should be dealing with Pint objects all the time

In the modules where computation occur, conversion to numerics happens hidden from the user

But maybe that's more of a medium-term goal :)

**Comment by HelgeGehring** [comment]
Pint sounds interesting! I'm wondering how much advantage is gives over just using SI-units, or if we could just use it for the final input/output?
Also I'm wondering if it will be problematic if we want somewhen to integrate something like jax?
Maybe we make a separate issue and discuss it in detail? :)

And still, we should converge on the axis labels (as this will be independent of pint a problem)
Are there any other official recommendations for the labels?

**Comment by HelgeGehring** [comment]
To get this closed: If there's no reason against it, we'll follow the SI-rules: https://www.bipm.org/en/publications/si-brochure 5.4.1
So the graphs should be labeled like
![image](https://user-images.githubusercontent.com/42973196/226240816-3bd26be5-cdce-4555-ac1e-7c4fce5cf4e1.png)
