### ISSUE TITLE
Live code in the docs is broken

### ISSUE THREAD

**Issue by simbilod** [HelgeGehring/femwell#35]
Does not seem to have slepc

![image](https://user-images.githubusercontent.com/46427609/223301845-2e4e4570-71d3-42e3-be4c-cbf19954302c.png)

**Comment by HelgeGehring** [comment]
where does that happen? to me the docs seems fine

**Comment by HelgeGehring** [comment]
ahh, thanks, I didn't add it yet to the mybinder image

**Comment by HelgeGehring** [comment]
should be fixed now :) it might be that mybinder wants still to use the old kernel - in that case either wait a day or use another browser :)
