### ISSUE TITLE
Not able to run compute_cross_section_modes

### ISSUE THREAD

**Issue by spnadig** [HelgeGehring/femwell#43]
error: ModuleNotFoundError: No module named 'petsc4py'
I tried -
pip install petsc4py (version - petsc4py 3.18.5), but this package has issues to install (for any version)
<img width="692" alt="image" src="https://user-images.githubusercontent.com/124022677/229241525-3b277588-ec37-42db-bbbf-a9654f5506a6.png">

**Comment by HelgeGehring** [comment]
Can you try
```
conda install slepc4py=*=complex* -y
```
?

I'll add it to the docs

**Comment by spnadig** [comment]
This worked (I am using mamba env)

**Comment by HelgeGehring** [comment]
:+1:  I'll close this issue once I added the instruction to the docs.

**Comment by spnadig** [comment]
also quick question  - does femwell work on any klayout component directly without re-defining it in python?

**Comment by simbilod** [comment]
We wrote a plugin to gdsfactory to directly mesh Components, see

https://gdsfactory.github.io/gdsfactory/notebooks/meshing/01_intro.html
https://gdsfactory.github.io/gdsfactory/notebooks/meshing/02_2D_xy_mesh.html
https://gdsfactory.github.io/gdsfactory/notebooks/meshing/03_2D_uz_mesh.html

You can convert any GDS cell into a gdsfactory component
https://gdsfactory.github.io/gdsfactory/_autosummary/gdsfactory.read.import_gds.html?highlight=import_gds

The last thing you'd need to do is define  LayerStack to properly tell the importer what structure the layers correspond to:
https://gdsfactory.github.io/gdsfactory/notebooks/03_layer_stack.html?highlight=layerstack#layerstack
If you define your LayerStack (mapping between layers and structure), after importing your GDS you s

**Comment by spnadig** [comment]
Great- thanks!
