### ISSUE TITLE
IndexError and Mesh Artifacts

### ISSUE THREAD

**Issue by st4eve** [HelgeGehring/femwell#47]
Code:
```
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import gdsfactory as gf
from tqdm.auto import tqdm
import numpy as np
from gdsfactory.technology import LayerStack



import sys
import logging
from rich.logging import RichHandler
import gdsfactory as gf

from amf_pdk_pkg import PDK, LAYER_STACK, strip_SiN, strip_SiN_only

from collections import OrderedDict

import matplotlib.pyplot as plt
import numpy as np
import shapely
import shapely.affinity
from scipy.constants import epsilon_0, speed_of_light
from shapely.ops import clip_by_rect
from skfem import Basis, ElementTriP0
from skfem.io.meshio import from_meshio

from femwell.maxwell.waveguide import compute_modes
from femwell.mesh import mesh_from_OrderedDict
from femwell.visualization import plot_domains


gf.config.rich_output()
PDK.activate()

logger = logging.getLogger()
logger.removeHandler(sys.stderr)
logging.basicConfig(level="WARNING", datefmt="[%X]", handlers=[RichHandler()])

filtered_layerstack = LayerStack(
    layers={
        k: LAYER_STACK.layers[k]
        for k in (
            "sin",
            "clad",
            "box",
        )
    }
)

resolutions = {}
resolutions["sin"] = {"resolution": 0.02, "distance": 2}
resolutions['clad'] = {"resolution": 0.2, "distance": 1}
resolutions['box'] = {"resolution": 0.2, "distance": 1}
c = gf.components.straight(cross_section=strip_SiN)
mesh = c.to_gmsh(
    type="uz",
    xsection_bounds=[(5, -5), (5, 5)],
    layer_stack=filtered_layerstack,
    filename=f"mesh.msh",
    resolutions=resolutions
)
mesh = from_meshio(mesh)
mesh.draw().show()

filtered_layerstack = LayerStack(
    layers={
        k: LAYER_STACK.layers[k]
        for k in (
            "sin",
            "clad",
            "box",
        )
    }
)

resolutions = {}
resolutions["sin"] = {"resolution": 0.02, "distance": 2}
resolutions['clad'] = {"resolution": 0.2, "distance": 1}
resolutions['box'] = {"resolution": 0.2, "distance": 1}
c = gf.components.straight(cross_section=strip_SiN)
mesh = c.to_gmsh(
    type="uz",
    xsection_bounds=[(5, -5), (5, 5)],
    layer_stack=filtered_layerstack,
    filename=f"mesh.msh",
    resolutions=resolutions
)
mesh = from_meshio(mesh)
mesh.draw().show()
```
Mesh:
![image](https://user-images.githubusercontent.com/79719770/232650123-41c8b80f-0a71-4b58-96ac-508d64c5ac4e.png)

Epsilon Plot SiN:
![image](https://user-images.githubusercontent.com/79719770/232650267-3c9b1178-662c-4ed2-be85-26122108e548.png)

Epsilon Plot Box:
![image](https://user-images.githubusercontent.com/79719770/232650351-f3bb9e3f-2a00-4c99-b884-c79c1a23b270.png)

When trying to create the epsilon plot for the cladding I get the following error:
`Traceback (most recent call last):
  File "/home/st4eve/Desktop/purple/mask-design/purple_headers/tristan_sim/mode_solving.py", line 65, in <module>
    epsilon[basis0.get_dofs(elements=subdomain)] = n**2
  File "/home/st4eve/miniconda3/envs/layout/lib/python3.10/site-packages/skfem/assembly/dofs.py", line 172, in __array__
    return self.flatten()
  File "/home/st4eve/miniconda3/envs/layout/lib/python3.10/site-packages/skfem/assembly/dofs.py", line 94, in flatten
    (self.obj
IndexError: index 9014 is out of bounds for axis 1 with size 9014`

**Comment by simbilod** [comment]
@st4eve we were following the docs, but it's possible something was off in the element definition

**Comment by st4eve** [comment]
`basis0 = Basis(mesh, ElementTriP0())
epsilon = basis0.zeros()
for subdomain, n in {"sin": 1.9963, "box": 1.444, "clad": 1}.items():
    epsilon[basis0.get_dofs(elements=subdomain)] = n**2
    basis0.plot(epsilon, colorbar=True).show()
    plt.show()`

This should be all of it. Apologies
