### ISSUE TITLE
Slepc/Slepc4py Installation using Pip

### ISSUE THREAD

**Issue by timurdogan** [HelgeGehring/femwell#48]
I am running into issues installing slepc4py  on Windows which requires petsc. 
Petsc seems to be requiring a UNIX version of cygwin.
![image](https://user-images.githubusercontent.com/74224252/233251041-ade6d901-b45c-44a8-a984-5b6abbdfc3e3.png)
https://petsc.org/main/install/windows/

I am not sure how to pass this step, can you help me with this?

**Comment by HelgeGehring** [comment]
Hey :)

did you try to install it via pip? It seems so, as it wants to build locally.

The recommended way by the petsc/slepc community is to install it using `conda`, i.e. executing
```
conda install slepc4py=*=complex*
```

The `pip` based install is often problematic, as it requires a lot of installed dependencies (which are way more complicated to install using windows).

Let me know if that works for you!

**Comment by HelgeGehring** [comment]
Okay, I just realized there are no packages for windows in coda :/

Thus possible solutions would be:

- Use the linux-subsystem to install conda and run things there, this can conveniently be used via e.g. VScode (https://code.visualstudio.com/docs/remote/wsl). This also allows to install conveniently a range of other open source packages like meep
- Use a linux computer (or mac) for the simulatons (either remote or local).
- Use a github codespace
- add `solver='scipy'` to calculate_modes. Using scipy is not fully tested at the moment, but we're working on that to ease the use of femwell. It seems, that the calculated effective refractive indices are correct, but the fields are sometimes superposed by a non divergence-free solution with zero eigenvalue, which falsifies the results for any calculation which needs the field distribution of the modes (like overlap integrals). But as said, we're working on this part.

Hope this helps :)

**Comment by timurdogan** [comment]
Thank you for your quick response.

I realized the Linux option and will try that.

This may be a stupid question but what does it mean to use a github
codespace? Does it allow you to run baremetal or it uses a
translation/emulation?

I tried scipy (quite slow in eigensolution) but I wanted to see it
in its intended state with slepc.

**Comment by joamatab** [comment]
Hi Erman,

code-spaces are web based virtual machines that github provides for your development

Another option is to use WSL
https://learn.microsoft.com/en-us/windows/wsl/install

Another option is using vscode with a remote server

scipy speed should be comparable to SLEPC, has anyone benchmarked both?

**Comment by HelgeGehring** [comment]
In my tests, scipy wasn't so slow, but I also didn't spent too much time with it. Often, you can adjust the mesh a bit and things are faster (hopefully we'll soon get automatic refinement, that will make finding the right mesh way simpler)

Maybe you could post an example which was slow for you and we can have a look if we can speed it up?

Benchmarking both is a great idea! I'll add it to the benchmark we have already!

**Comment by timurdogan** [comment]
Thank you for all the help, everyone. If anyone benchmarked scipy vs slepc, please update here.

**Comment by HelgeGehring** [comment]
The scipy benchmarks are online! The calculation of the eigenvalues seems as precise as with slepc!

@timurdogan

**Comment by timurdogan** [comment]
Thank you, numbers look good.
