### ISSUE TITLE
femwell pip install outdated

### ISSUE THREAD

**Issue by JimohYusuf** [HelgeGehring/femwell#49]
When I pip install femwell, I get the following: No module named 'femwell.maxwell'

I think the examples use more recent code than the pypi package.

**Comment by HelgeGehring** [comment]
Thanks for the feedback!

I've now published a new pip-version! You can update via `pip install --upgrade femwell`

Let me know if that fixes the problem for you :)

**Comment by JimohYusuf** [comment]
Hi. I cloned and installed directly from the repo already and it worked fine. If the new pip version is from the current repo then it's all good.

Thank you!

**Comment by HelgeGehring** [comment]
Perfect! So I'll close this.
