### ISSUE TITLE
Periodic meshes

### ISSUE THREAD

**Issue by HelgeGehring** [HelgeGehring/femwell#6]
Could we allow the meshing to do periodic meshes? @simbilod

**Comment by HelgeGehring** [comment]
Update @simbilod : the mesh doesn'y need to provide information that it's symmetric, the two boundaries just need to be conformal to use master-slave-constraints

**Comment by HelgeGehring** [comment]
https://github.com/HelgeGehring/femwell/pull/25 allows periodic meshes for parallel lines!
As described there, two things are missing:
[] checks
[] more logic to handle intersection geometries with periodic walls

**Comment by simbilod** [comment]
Also see v0.1.0 of [meshwell](https://github.com/simbilod/meshwell) for 3D version
