### ISSUE TITLE
Mode selection seems broken

### ISSUE THREAD

**Issue by simbilod** [HelgeGehring/femwell#63]
See docs https://helgegehring.github.io/femwell/photonics/examples/selecting_modes.html, nitride mode is not being sorted correctly

**Comment by HelgeGehring** [comment]
Do you mean the last way to find the mode?

**Comment by simbilod** [comment]
Yes it's selecting silicon as is, but we are asking for SiN

**Comment by HelgeGehring** [comment]
@simbilod should be fixed now, let's check after the docs rebuilt
