### ISSUE TITLE
Fail to Live Launch and also Import from OrderedDict on Google Colab

### ISSUE THREAD

**Issue by sherijahan** [HelgeGehring/femwell#71]
@HelgeGehring @simbilod @mdecea @joamatab 
Hi, I have tried to use the live launch on example code but they fail. Also, I tried to run the codes on Google colab but its seems it fails to import from "OrderedDict".
The following is the error I get. Could you help? Thanks

**_"---------------------------------------------------------------------------

OSError                                   Traceback (most recent call last)

[<ipython-input-15-8ef9e32c7ecf>](https://localhost:8080/#) in <cell line: 9>()
      7 from skfem.io import from_meshio
      8 
----> 9 from femwell.mesh import mesh_from_OrderedDict
     10 from femwell.thermal import solve_thermal
     11 

3 frames

[/usr/lib/python3.10/ctypes/__init__.py](https://localhost:8080/#) in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    372 
    373         if handle is None:
--> 374             self._handle = _dlopen(self._name, mode)
    375         else:
    376             self._handle = handle

OSError: libGLU.so.1: cannot open shared object file: No such file or directory"_**

**Comment by sherijahan** [comment]
Now I also see
"ModuleNotFoundError: No module named 'skfem'"

**Comment by joamatab** [comment]
How did you launch? there is a launch button at the top

![image](https://github.com/HelgeGehring/femwell/assets/4514346/8a09030e-cf6f-4aa0-b097-638f16f2aaaa)

**Comment by sherijahan** [comment]
Yes, it fails here and then I tried in Google Colab platform where the above screenshot error came up. Any idea how to get around? Thanks

**Comment by joamatab** [comment]
why not install it and run locally?

these free compute instances are pretty week anyway

**Comment by HelgeGehring** [comment]
@sherijahan it should be fixed now :)

For colab you probably need to execute once "!apt install gmsh" to fix that error

But I agree with @joamatab , the server for the live-examples has only limited computing power and is intended for playing a bit with the examples to understand them better, so if precision is required, either running it locally or on stronger cloud services are advisable.

Could you check if it's working for you, too? Thanks!

**Comment by HelgeGehring** [comment]
@sherijahan is it now working for you?

**Comment by sherijahan** [comment]
Hi @HelgeGehring sorry for going MIA. Just checked. Yes it works for both the live launch and google collab for me. Thank you for the solutions.

**Comment by HelgeGehring** [comment]
Yay, thanks for confirming :)
I'll close this issue!
